sudo: required
services:
  - docker
language: c
cache: false

notifications:
  email:
    recipients:
      - richard.mortier+www-build@gmail.com
    on_success: never
    on_failure: never

before_install:
  - sudo add-apt-repository -y ppa:avsm/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y realpath # needed on ubuntu 14.04.5 LTS / trusty
  - sudo apt-get install -y opam && opam init
  - wget https://raw.githubusercontent.com/mor1/dommage/master/dommage
  - wget https://raw.githubusercontent.com/mor1/dommage/master/dommage-deploy
  - chmod +x dommage dommage-deploy
  - export PATH=$PATH:$PWD/

script:
  - mkdir _site _mirage/_build
  - make site configure build
  - dommage-deploy

env:
  matrix:
    - FLAGS="-t unix -vv --net socket"
    - FLAGS="-t unix -vv --net direct"
    - FLAGS="-t xen  -vv --net direct --dhcp false --interface 0
        --ipv4 46.43.42.137/25 --ipv4-gateway 46.43.42.129"
      DEPLOY=1 XENIMG="mortio" UPDATE_GCC_BINUTILS=1 MIRDIR="_mirage"

  global:
    - secure: aJr69EvXZrAoAxICpXc71SVobUb44A3BFwP+KPWCQUNyuQLn56jYeq6qjVmNwCyXGQj/67Crl5P0+XTGkUDk2jOZCuRBl3jq8oy9PbSCg4ptPBL5F/w1BZfcYAv2NvwuM2OOwdyLSdw9WXk2lOWmNAb+4tR2qkROYgcDCqF0a9Q=
    - secure: BMciH1rAKkv7OKEvM4Vqe+VYKZyYEViB/gYjqYwGfsIr/poeBLFXX6dRm8Uzn3APTm29ig67rlrRH9zzlVy0V08GiEzcY7JatlkC1RSbpH5Rp9MSfVu925QlcHyIUo6yLJDQDAnyr4NxW6OdeZfgp9uFCdN/xCsHLbT3IjBXBZg=
    - secure: ZeHUTIcBjFaKR/HAnpZPwmglrCfSTVlvLDs1zHkZSoyAXiOd9p71BMLNE+fqF/yewv2Ospljju/mGwQ3bjy6jrK9j/pJiljh5lBeSJoDd/1y4qov6AXqmxg6MranI1VgbbjyIv636wy7Fz0JJNnrY0blntLDN1vAFs3MlgwzSZ4=
    - secure: YVwB1/abrD7UicEtU0N2wFYeyvcPjnbIjP9geRYZz9dUqlZNYWjyiaCB/b5J7YcdhGW0i+kpC2r+OWuxeoz9LxsGAxGmVG+LKxQrMxwebI+EOhvRcAlUaXlbZ/6Nk0HbfKpe7VdfrIKNPSrGGSw+qk7DtpMoeKBo6rZzD0AgIIs=
    - secure: HGkAo+ytn0e6+PtnIT4bEgByjc5tCofvYYNKuqTvgzDIkLvziEl7ptZxaE+7JVNDdt1v2QpQqkUlUVczPW53l97f0kcX47MsBKSU4+lGQ5sMAGn+Y3Dweycd2UZoJEUVyHUGM4i/yxMatVW6VFwQ8AVqa/FvxPk/07FEbk4CcGk=
    - secure: DJ7voeAKs9P4UXVYWZgTSok9iYjq7XyoQkhRuTvu4pwfWIuQZJN0f8mKxMEK8qQUsWc0zvnuAFQQVBcWpN+/J+JW6uE5GjrxJc2AyWgtvpChqaNyfrwbAf3wCaqo5mrT7XHkZs7wHDxQA2c9803ohEvpfFcHK6I4HscRnE/JUtI=
    - secure: UR8hj9Py5+7AcBAJDaTbLpFmkafKbmsxnxVcn0Ec2ePF7ptqAseDIx+0d1Tc7YxyhQGSTVu81bl2UiMNE6khRdX2arlh5dJ7ViGPps0Ide5aLMpNHKokjsqVsVgHLnpiFXECwJLSG+WbfJmivDK9mvNFchnOKpFIEmYFjm3RXoI=
    - secure: aXoV36MxotbwdfFjrZngNMPJXunI3iZouJZXruN26YDFV+gIO0hwD2BEKk8hCFSlj9FIQNWG2iqZhdEhQyfN0ze+gtoZP7xC2H5Xp0gfx2XsFFI+Xq6HoamyrolXy5aR7gfXYJLI+fKFO9+ZNBLOCqdB0Yg1AFrlrTRvXtBuInQ=
    - secure: W6JO7PzdHx/oct7dO84LeP6GSoT5NX+yZU4DC+U/aZtnDa92mIn3cyhOjp6GSryTc8oiHM4Z7goZwYDeXqJ2zC8cvT+DdZSszCQYAle6F05UFKUAD0raZNQbun3BU98NhEC3I6FZi0mzNJRD5ajxYbrFZc6xlSXaiTXBAnGkYp4=
    - secure: gMz+B/nX9gmOn1XZoOcnpZhuGCmFIVhZydwDh00pbNfDOxlsIU44NPhkOLG5ZXktb409KqCK+oGkCto86LtykloOht9xUxEQ7EQfZwV0J4TAtf2kpjYHiHYX1ZFAThTzw8cO/+rB+Y22sMFDwcJDKd7GJJmMhhXzmOfZQ0ngqCA=
    - secure: L6DUG1aIit2IE5S//ofbzd+MLpi/6JgMdGpMahrQC0E3obz91E9v/CgZTIeyBE8Ed5C721ELaIZmE3fbQ+FmsIbmqTa1QTRl0kF05942P4xmij/DvQiiYSRypJjvWI08MoqiO5sPvDQ3Eu/Sn+Q502/hxv0wfK00LB4MnQ+TLFI=
    - secure: S6g2Bja6TEygqbnMXfDD+t7ozVvWZ0KxPWy4UE+bEsInvyMHh3p8hsMpx8dGbBJHIh1sgX4pnIjqVMWbzrwiceTb5ARRSxMnEW3AuvGyRxvFWtR3qUh5mwVXF5UmgNoRP1xpP2p3D0Bd4PmM/8ipm65JpRKRxw8zwrVYvZB3Zsw=
    - secure: Kyh/DnHAmAHisGGWogCMpUQlxGFPB81nHlLpColpVOCm/n+q9uap0xnwAV+WZmrQCFL5TU9NJx9BeZ/3hUo504X7b4dc+WdRsCyvM4y6w6fbGR8W5whHiGJt/fyCtGaEt/S6GS0J/tV7nUoOPjbkbOCk7IMxQHd2dF1O3Tjxo2c=
