sudo: required
services:
  - docker

notifications:
  email:
    recipients:
      - richard.mortier+www-site@gmail.com
    on_success: always
    on_failure: always

script:
  - make jss
  - git add js && git commit -m 'autobuild $(JSS)' && git push

deploy:
  provider: pages
  target_branch: master # user repo so doesn't use branch `gh-pages`
  skip_cleanup: true
  on:
    branch: source

  github_token:
    - secure: "WrlO92kGWHTWzm05I38xdcRMuiLLGy2TrfxApRzyRUTvmMZpVWT8g/18wv/rjtO1SoLOcy5vpLtdQBMnKkKVQY2Ux+46FY7gZsknd/wd+8XS2OcMRYXRht7myLSakok5tUuWlKv+HnKGNa9H8ccznDSCb1Qk0oNWHN+oUt+gAYQ="
