#
# Copyright (c) 2012--2015 Richard Mortier <mort@cantab.net>
#
# Permission to use, copy, modify, and distribute this software for any purpose
# with or without fee is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#

## jekyll configuration, enforced
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax

## jekyll configuration, can be overridden
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate

## my configuration
exclude: [Makefile, README.md, _coffee, _mirage]
include: [.well-known]
permalink: pretty

## fix fenced syntax highlighting for mirage build at least
kramdown:
  syntax_highlighter: coderay

domain: mort.io
title: mort's mythopoeia ##'
author: Richard Mortier
email: mort@cantab.net
analytics_id: UA-15796259-1
gems:
- jekyll-sitemap

navigation:
- text: home
  url: /
- text: research
  url: /research/
- text: teaching
  url: /teaching/
- text: codes
  url: /codes/
- text: me
  url: /me/
